#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 13 20:59:13 PYST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1 + EuphoriaPatches_1.6.4.zip
