#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 13 20:47:14 PYST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
